# Generated by Django 2.2.1 on 2019-06-03 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroModel',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to=settings.AUTH_USER_MODEL)),
                ('data_nascimento', models.DateTimeField(verbose_name='Data de Nascimento')),
                ('sobre_voce', models.TextField(max_length=500, verbose_name='Fale mais sobre você')),
                ('objetivos_profissionais',
                 models.TextField(max_length=500, verbose_name='Fale sobre seus objetivos profissionais')),
                ('sexo', models.CharField(choices=[('1', 'MASCULINO'), ('2', 'FEMININO'), ('0', 'OUTROS')], default='1',
                                          max_length=10, verbose_name='Sexo')),
                ('deficiencia', models.CharField(
                    choices=[('1', 'FÍSICA'), ('2', 'AUDITIVA'), ('3', 'VISUAL'), ('4', 'INTELECTUAL'),
                             ('5', 'MÚLTIPLA'), ('6', 'READAPTADO'), ('0', 'NENHUMA')], default='0', max_length=10,
                    verbose_name='Deficiência')),
                ('telefone', models.CharField(blank=True, max_length=16, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=16, verbose_name='Celular')),
                ('telefone_recado', models.CharField(blank=True, max_length=16, verbose_name='Telefone para recados')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContatoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('github', models.URLField(blank=True, default='', verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, default='', verbose_name='LinkedIn')),
                ('facebook', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('portfolio', models.URLField(blank=True, default='', verbose_name='Portfolio')),
                ('endereco', models.CharField(default='', max_length=100, verbose_name='Endereço')),
                ('endereco_numero', models.CharField(default='', max_length=5, verbose_name='Número')),
                ('endereco_complemento',
                 models.CharField(blank=True, default='', max_length=30, verbose_name='complemento')),
                ('endereco_cidade', models.CharField(default='', max_length=30, verbose_name='cidade')),
                ('endereco_estado', models.CharField(
                    choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'),
                             ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'),
                             ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'),
                             ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Acre'), ('PI', 'Piauí'),
                             ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'),
                             ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'),
                             ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')],
                    default='SP', max_length=20, verbose_name='estado')),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
