# Generated by Django 2.2.2 on 2019-06-17 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastromodel',
            name='data_nascimento',
            field=models.DateTimeField(default=datetime.date(2000, 1, 1), verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='cadastromodel',
            name='objetivos_profissionais',
            field=models.TextField(default='Meus objetivos profissionais são ...', max_length=500, verbose_name='Fale sobre seus objetivos profissionais'),
        ),
        migrations.AlterField(
            model_name='cadastromodel',
            name='sobre_voce',
            field=models.TextField(default='Sou uma pessoa que...', max_length=500, verbose_name='Fale mais sobre você'),
        ),
    ]
