# Generated by Django 2.2.2 on 2019-06-27 23:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aluno', '0002_auto_20190617_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedesSociaisModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('github', models.URLField(blank=True, default='', verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, default='', verbose_name='LinkedIn')),
                ('facebook', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('portfolio', models.URLField(blank=True, default='', verbose_name='Portfolio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SobreMimModel',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data_nascimento', models.DateTimeField(default=datetime.date(2000, 1, 1), verbose_name='Data de Nascimento')),
                ('sobre_voce', models.TextField(default='Sou uma pessoa que...', max_length=500, verbose_name='Fale mais sobre você')),
                ('objetivos_profissionais', models.TextField(default='Meus objetivos profissionais são ...', max_length=500, verbose_name='Fale sobre seus objetivos profissionais')),
                ('sexo', models.CharField(choices=[('1', 'MASCULINO'), ('2', 'FEMININO'), ('0', 'OUTROS')], default='1', max_length=10, verbose_name='Sexo')),
                ('deficiencia', models.CharField(choices=[('1', 'FÍSICA'), ('2', 'AUDITIVA'), ('3', 'VISUAL'), ('4', 'INTELECTUAL'), ('5', 'MÚLTIPLA'), ('6', 'READAPTADO'), ('0', 'NENHUMA')], default='0', max_length=10, verbose_name='Deficiência')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contatomodel',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contatomodel',
            name='github',
        ),
        migrations.RemoveField(
            model_name='contatomodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contatomodel',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='contatomodel',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='contatomodel',
            name='celular',
            field=models.CharField(blank=True, max_length=16, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='contatomodel',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='contatomodel',
            name='telefone_recado',
            field=models.CharField(blank=True, max_length=16, verbose_name='Telefone para recados'),
        ),
        migrations.AlterField(
            model_name='contatomodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CadastroModel',
        ),
    ]
