# Generated by Django 2.2.2 on 2019-07-01 19:26

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('aluno', '0004_faculdademodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculdademodel',
            name='carga_horaria',
            field=models.IntegerField(blank=True, default='2400', verbose_name='Carga Horária do curso'),
        ),
        migrations.AlterField(
            model_name='faculdademodel',
            name='curso',
            field=models.CharField(default='', max_length=100, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='faculdademodel',
            name='data_fim',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 1, 0, 0, 0, 127325, tzinfo=utc),
                                       verbose_name='Previsão de término'),
        ),
        migrations.AlterField(
            model_name='faculdademodel',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.date(2019, 1, 1), verbose_name='Início do curso'),
        ),
        migrations.AlterField(
            model_name='faculdademodel',
            name='instituicao',
            field=models.CharField(default='', max_length=100, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='faculdademodel',
            name='situacao',
            field=models.CharField(choices=[('0', 'em andamento'), ('1', 'concluído'), ('2', 'não concluído')],
                                   default='0', max_length=10, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='faculdademodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
